### ISSUE TITLE
Add an instance instead of a variable to call the logger

### ISSUE THREAD

**Issue by tomiok** [tomiok/tomatto-logger#2]

**Comment by hugolesta** [comment]
Hey @tomiok. Could you please add a description on this Issue? I'd like to help you with this. Thanks

**Comment by tomiok** [comment]
Sure @hugolesta, the idea is that the main logger is a variable in file logs.go line 13. So if anyone call the `logs.Info(i interface{})` function, works on the top of a variable, which is a weak design in concurrent environments.

The main idea for this is to use a struct and keep working with the function, not a method.

If you check out Uber's Zap logger, the use a method for the loggers, that a good idea also but not as flexible as I wish.

Hope this clarify something dude.

**Comment by hugolesta** [comment]
Nice! Thanks so much for the hint. I thought to use struct instead of variable, you know, I wanted to be sure about that.
